---
title: Class Script
subtitle: "Linear Regression - Classworks 2 & 3"
author:
  - name: Byeong-Hak Choe
    
date: 2026-02-04

execute: 
  echo: true
  eval: true
  warning: false
  message: false
  fig-width: 10
  fig-height: 6

format:
  html:
    code-fold: true
    toc: true
    toc-title: "Contents"
    toc-expand: 3
    number-sections: true
    code-tools: true
    highlight-style: atom-one
---

```{r setup}
#| include: false
library(tidyverse)
library(skimr)
library(ggthemes)
library(hrbrthemes)
library(DT)
library(stargazer)
library(broom)

theme_set(theme_ipsum()+
          theme(strip.background =element_rect(fill="lightgray"),
                axis.title.x = 
                  element_text(angle = 0,
                               size = rel(1.33),
                               margin = margin(10,0,0,0)),
                axis.title.y = 
                  element_text(angle = 90,
                               size = rel(1.33),
                               margin = margin(0,10,0,0))
                )
          )
```


# R packages
```{r}
library(tidyverse)
library(broom)
library(stargazer)
library(skimr)
```


# Classwork 2

```{r}
bikeshare <- read_csv("https://bcdanl.github.io/data/bikeshare_cleaned.csv")

bikeshare_sum <- bikeshare |> 
  skim()
```

## Q2

```{r}
bikeshare <- bikeshare |> 
  mutate(year = factor(year),
         year = fct_relevel(year, "2011"),
         seasons = factor(seasons,
                          levels = 
                            c("spring", 
                              "summer", 
                              "fall",
                              "winter")),
         month = factor(month),
         month = fct_relevel(month, "01"),
         hr = factor(hr),
         hr = fct_relevel(hr, "0"),
         wkday = factor(wkday,
                          levels = 
                            c("sunday", "monday", "tuesday", "wednesday", "thursday", "friday", "saturday")),
         weather_cond = factor(weather_cond,
                          levels = 
                            c("Clear or Few Cloudy", 
                              "Light Snow or Light Rain",
                              "Mist or Cloudy")),
         )
  
# unique(df_bike$weather_cond)
# levels(df_bike$seasons)  
# levels(df_bike$month)  
# levels(df_bike$hr)  
```

```{r}
set.seed(1)

bikeshare <- bikeshare |> 
  mutate(rnd = runif(n()))

dtrain <- bikeshare |> 
  filter(rnd > 0.4)

dtest <- bikeshare |> 
  filter(rnd <= 0.4)

nrow(dtrain) / nrow(bikeshare)
```




## Q3

```{r}
model <- lm(cnt ~ temp + hum + windspeed + 
                  year +
                  month + 
                  hr + 
                  wkday +
                  holiday +
                  seasons +
                  weather_cond,
            data = dtrain)

stargazer(model, type = "text")

model_out_1 <- tidy(model, conf.int = T)
model_out_2 <- glance(model)
model_out_3 <- augment(model)

# rm(model_out)
```

## Q4

```{r}
dtest <- dtest |> 
  mutate(pred = predict(model, newdata = dtest),
         .before = 1)
```


## Q5
-4.965

## Q6

```{r}

stargazer(model, type = "text")

model_out_hr <- model_out_1 |> 
  filter(str_detect(term, "hr")) |> 
  arrange(-abs(estimate))


```
hr17
378.85232



## Q7
Draw a coefficient plot for `temp`, `hum` and `windspeed` variables.


```{r}
model_out_1 |> 
  filter(term %in% c("temp", "hum", "windspeed")) |> 
  ggplot(
    aes(xmin = conf.low, 
        xmax = conf.high,
        x = estimate,
        y = term)
  ) +
  geom_pointrange() +
  geom_point() +
  geom_vline(xintercept = 0, color = "darkorange", linetype = 2) 
```


Draw a coefficient plot for month variables.


```{r}
stargazer(model,
          type = "text")
```

```{r}
#| fig-height: 8
model_out_1 |> 
  filter(str_detect(term, "month")) |> 
  ggplot(
    aes(xmin = conf.low, 
        xmax = conf.high,
        x = estimate,
        y = term)
  ) +
  geom_pointrange() +
  geom_point() +
  geom_vline(xintercept = 0, color = "darkorange", linetype = 2) 
```


Draw a coefficient plot for hr variables.
Draw a coefficient plot for wkday variables.
Draw a coefficient plot for seasons variables.
Draw a coefficient plot for weather_cond variables.
