---
title: Class Script
subtitle: "Decision Trees"
author:
  - name: Byeong-Hak Choe
    
date: 2026-03-30

execute: 
  echo: true
  eval: true
  warning: false
  message: false
  fig-width: 10
  fig-height: 6

format:
  html:
    code-fold: false
    toc: true
    toc-title: "Contents"
    toc-expand: 3
    number-sections: true
    code-tools: true
    highlight-style: atom-one
---

# Setup

```{r setup}
#| include: false

library(tidyverse)
library(janitor)
library(ggthemes)
library(rmarkdown)

library(rpart)
library(rpart.plot)
library(vip)
library(pdp)

theme_set(
  theme_bw() +
    theme(
      legend.position = "bottom",
      strip.background = element_rect(fill = "lightgray"),
      axis.title.x = element_text(size = rel(1.1)),
      axis.title.y = element_text(size = rel(1.1))
    )
)

```


# Data


```{r}
nbc <- read_csv("https://bcdanl.github.io/data/nbc_show.csv") |> 
  janitor::clean_names()  # column names are with all lowercase; 
                          # spaces in column names are replaced by _

paged_table(nbc)
```


```{r}
nbc_demog <- read_csv("https://bcdanl.github.io/data/nbc_demog.csv") |> 
  janitor::clean_names()

paged_table(nbc_demog)
```


# Viz

```{r}
nbc |>
  ggplot(aes(x = grp, y = pe, color = genre)) +
  geom_point(size = 2, alpha = 0.8) +
  geom_smooth(method = "lm", se = FALSE) +
  labs(
    title = "GRP and Projected Engagement by Genre",
    x = "Gross Ratings Points (GRP)",
    y = "Projected Engagement (PE)",
    color = "Genre"
  )
```

```{r}
init_nbc_tree <- rpart(
  pe ~ grp + genre,
  data = nbc,
  method = "anova" # regression tree
)
```




```{r}
init_nbc_tree
```

```{r}
full_nbc_tree <- rpart(
  pe ~ grp + genre,
  data = nbc,
  method = "anova",
  control = rpart.control(cp = 0, xval = 10, minsplit = 2)
)
```


```{r}
full_nbc_tree
```


```{r}
rpart.plot(full_nbc_tree)
```

```{r}
plotcp(full_nbc_tree)

```



# VIP

```{r}
vip(full_nbc_tree, geom = "col")  # “col”, “point”, “boxplot”, “violin”
```


```{r}
# Partial Dependence for `grp`
partial(full_nbc_tree, pred.var = "grp") |>
  autoplot() +
  labs(title = "Partial Dependence of PE on GRP")
```



# Pruning

```{r}
boston <- read_csv("https://bcdanl.github.io/data/boston.csv") |>
  janitor::clean_names()

paged_table(boston)
```

```{r}
set.seed(42120532)
boston <- boston |> 
  mutate(rnd = runif(n()))

dtrain <- boston |> 
  filter(rnd > .2) |> 
  select(-rnd)

dtest <- boston |> 
  filter(rnd <= .2) |> 
  select(-rnd)

x_train <- dtrain |> select(-medv)
y_train <- dtrain$medv
x_test  <- dtest |> select(-medv)
y_test  <- dtest$medv
```



```{r}
boston_tree <- rpart(
  medv ~ ., 
  data = dtrain,
  method = "anova",
  control = rpart.control(cp = 0, xval = 10, minsplit = 10)
)

boston_tree
```


```{r}
rpart.plot(boston_tree)
```


```{r}
plotcp(boston_tree)
```

```{r}
cp_table_boston <- boston_tree$cptable |> 
  as_tibble()

cp_table_boston |> 
  paged_table()
```


```{r}
min_xerror_boston <- min(cp_table_boston$xerror)
min_row_boston <- cp_table_boston |>
  filter(xerror == min_xerror_boston) |>
  slice(1)


# alpha.min
cp_min_boston <- min_row_boston |> 
  pull(CP)

# 1-SE rule
# xerror_threshold_boston <- min_row_boston$xerror + min_row_boston$xstd

# alpha.1se
# cp_1se_boston <- cp_table_boston |>
#   filter(CP > 0, xerror <= xerror_threshold_boston) |>
#   arrange(nsplit) |>
#   slice(1) |>
#   pull(CP)

# pruned_boston_tree <- prune(boston_tree, cp = cp_1se_boston)
pruned_boston_tree <- prune(boston_tree, cp = cp_min_boston)


cp_min_boston
cp_1se_boston
```


```{r}
rpart.plot(pruned_boston_tree)
```


```{r}
vip(boston_tree)
```

```{r}
vip(pruned_boston_tree)
```



